version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 565393042665.dkr.ecr.ap-northeast-1.amazonaws.com

      - REPOSITORY_URI=565393042665.dkr.ecr.ap-northeast-1.amazonaws.com/myapp-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      # 为 Docker Hub 也打上标签
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $DOCKERHUB_USERNAME/myapp:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $DOCKERHUB_USERNAME/myapp:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

      - echo Pushing the Docker image to Docker Hub...
      - docker push $DOCKERHUB_USERNAME/myapp:$IMAGE_TAG
      - docker push $DOCKERHUB_USERNAME/myapp:latest

      - echo Writing image definitions file...
      - printf '[{"name":"MyAppContainer","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
